[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"
[project]
name = "pydesk-json-tools"
version = "0.1.1"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
description = "PyDeskTools isolated plugin architecture"
dependencies = ['pydesktools-sdk>=0.1,<0.2', 'simplejson>=3.20,<4']
[tool.setuptools.packages.find]
where = ["src"]
[tool.setuptools.package-data]
"*" = ["py.typed", "locales/**/*.mo"]
